### ISSUE TITLE
kubectl apply of crd yaml fails on k8s 1.14

### ISSUE THREAD

**Issue by matthias50** [cybozu-go/topolvm#38]
**Describe the bug**
```kubectl apply -f topolvm/deploy/manifests/crd.yaml ``` fails with:

```error: error validating "crd.yaml": error validating data: ValidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec; if you choose to ignore these errors, turn validation off with --validate=false```

**Environments**
- Version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:21:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- OS: N/A

**To Reproduce**
1. kubectl apply -f topolvm/deploy/manifests/crd.yaml 
2. See error mentioned above.

**Expected behavior**
Yaml manifest applies successfully.

**Additional context**
It looks like preserveUnknownFields  is a 1.15 feature per https://kubernetes.io/blog/2019/06/19/kubernetes-1-15-release-announcement/, but the min version for TopoLVM is 1.14. I tried removing the field from the manifest and the kubectl apply worked, but I'm not sure if this is going to cause breakage later.

**Comment by ymmt2005** [comment]
Thank you.  We were too hasty.

Will fix.
