### ISSUE TITLE
Does topolvm-hook and csi-topolvm-controller support redundancy?

### ISSUE THREAD

**Issue by matthias50** [cybozu-go/topolvm#40]
I noticed there is only one replica for the topolvm-hook https://github.com/cybozu-go/topolvm/blob/master/deploy/manifests/mutatingwebhooks.yaml#L41 and https://github.com/cybozu-go/topolvm/blob/master/deploy/manifests/csi-controller.yaml#L186. Is it possible to run multiple replicas of these to improve availability/reliability?

**Comment by ymmt2005** [comment]
`topolvm-hook` can run multiple instances.

I'm afraid the current `csi-topolvm-controller` cannot be run as `Deployment`
because it does not implement leader election.  We will investigate this option
later.

**Comment by ymmt2005** [comment]
Addressed with #58.  Will be available in the upcoming 0.2.0.
