### ISSUE TITLE
Test matrix for Kubernetes versions

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/topolvm#42]
## What

Since TopoLVM supports Kubernetes 1.14 and 1.15, e2e tests should be run on both versions.

This should resolve #38 at the same time.

## How

Describe how to address the issue.

## Checklist

- [ ] Finish implentation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by binoue** [comment]
I think it would be better if this task includes testing `Getting Started` example too because `Getting Started` example can also be obsolete or broken when versioning up.

See this pull request: https://github.com/cybozu-go/topolvm/pull/44
