### ISSUE TITLE
Error message is not containing what volume group was not  able to access.

### ISSUE THREAD

**Issue by llamerada-jp** [cybozu-go/topolvm#80]
**Describe the bug**

Error message from `lvmd` command is not containing what volume group was not able to access.

It is a example of logs.
```
Dec 18 05:16:48 localhost systemd[1]: Started /home/core/lvmd --volume-group=myvg --listen=/run/topolvm/lvmd.sock --spare=1.
Dec 18 05:16:48 localhost lvmd[22326]: Error: not found
Dec 18 05:16:48 localhost lvmd[22326]: not found
```

**Environments**
- Version: TopoLVM v0.2.1

**To Reproduce**
Execute `lvmd` without create volume group that access from it.

**Expected behavior**
Output volume group information that `lvmd` could not access.

**Comment by ymmt2005** [comment]
Not a bug.
