### ISSUE TITLE
Unable to run kind example in Ubuntu 16.04

### ISSUE THREAD

**Issue by ridv** [cybozu-go/topolvm#87]
**Describe the bug**

Running `make run` fails with the following error:

```
/usr/local/bin/kubectl apply -f podpvc.yaml
Error from server (InternalError): error when creating "podpvc.yaml": Internal error occurred: failed calling webhook "pvc-hook.topolvm.cybozu.com": Post https://controller.topolvm-system.svc:443/pvc/mutate?timeout=30s: x509: certificate signed by unknown authority
Error from server (InternalError): error when creating "podpvc.yaml": Internal error occurred: failed calling webhook "pod-hook.topolvm.cybozu.com": Post https://controller.topolvm-system.svc:443/pod/mutate?timeout=30s: x509: certificate signed by unknown authority
```

**Environments**
- Version: Master
- OS: Ubuntu 16.04

**To Reproduce**
1. Enter `example` directory
2. Run `make setup`
3. Run `make run`

**Expected behavior**
After running `make run` I expect the node to be provisioned with the correct setup in order to create a pod using the volume created by the lvmd.

**Additional context**
None

**Comment by satoru-takeuchi** [comment]
@ridv Our team have only been used TopoLVM in Ubuntu 18.04. Is it possible to reproduce your problem in Ubuntu 18.04?

**Comment by satoru-takeuchi** [comment]
I'll try to reproduce this problem in my Ubuntu 16.04 environment. Please wait for a while.

**Comment by binoue** [comment]
@ridv 

Thank you for reporting!

We tried to reproduce this error in our Ubuntu 16.04 environment, but we could not do it.
Could you follow the steps below and check if the same error occurs? 

 1. cd ./example
 2. make clean
 3. make setup
 4. make run

If you encounter it again, please share the outputs of the following commands.

- `make setup`
- `make run`
- `/usr/local/bin/kubectl version`
- `kubectl get mutatingwebhookconfiguration topolvm-hook -o yaml`

**Comment by ridv** [comment]
Ok, it looks like the issue is on my side then! I was able to get this working with a vanilla [bento ubuntu 16.04 image](http://chef.github.io/bento/).

Only thing I had to do was tweak the monitoring for the time out from 60 to 120 seconds over here https://github.com/cybozu-go/topolvm/blob/master/example/Makefile#L21

Thanks for looking into it and sorry it ended up being an error on my side 😄

**Comment by masa213f** [comment]
@ridv 
Thanks. We didn't care about the timeout value.
We extended it based on your report!
