### ISSUE TITLE
webhook: incomplete information, stale result

### ISSUE THREAD

**Issue by pohly** [cybozu-go/topolvm#97]
**Describe the bug**

When a pod gets created, the mutating webhook tries to compute how much storage the pod will need on a node. The underlying problem with this approach is that the situation can change between pod creation and pod scheduling, with the result that the pre-calculated size may be incorrect or even impossible to calculate.

For example:
- Storage class and/or PVC might not have been created yet. This is valid. The Pod is then in a state where it cannot be scheduled due to missing volumes, but without the webhook installed, such a Pod can be created. With the webhook installed, pod creation gets rejected with an error here: https://github.com/cybozu-go/topolvm/blob/7b79ee30e997a165b220d4519c784e50eaec36c8/hook/mutate_pod.go#L129-L136
- A pod might use one volume. Pod scheduling fails because there is no node with enough storage. The user notices that and changes the PVC such that it uses a smaller volume, one that would fit onto a node. Pod scheduling continues to fail because the pre-computed resource quantity doesn't get adapted.

**Expected behavior**

Pod creation should work, and it should check conditions at the time when scheduling happens.

In PMEM-CSI I started implementing a similar webhook + scheduler extender approach. To minimize the impact of this problem, that webhook only treats the resource as a boolean flag: it gets set to 1 if (and only if) the pod uses a volume that needs to be provided by PMEM-CSI. The scheduler extender then is the one which computes the amount of space that's still needed.

This is still not perfect: in the case when the storage class and/or PVC are not defined at pod creation time, the webhook allows pod creation without the flag, i.e. that ends up getting scheduled without the scheduler extender although it isn't certain that it doesn't use PMEM-CSI.

The webhook could be eliminated entirely, but then *all* pods would have to involve the scheduler extender. I'm worried that the overhead would be too high in a cluster where only few pods really use it, and it creates the chicken-and-egg problem where the PMEM-CSI pods themselves cannot be scheduled because the extender isn't up yet.

**Comment by satoru-takeuchi** [comment]
Thank you for the report.  We admit these are bugs in the current implementation. In most use-cases, however, these are not severe problems since most users will use TopoLVM through StatefulSet with volume claim templates and, with that, all necessary PVCs are created before the Pod.

We'd like to leave this as a limitation of TopoLVM for now.

**Comment by pohly** [comment]
> most users will use TopoLVM through StatefulSet with volume claim templates and, with that, all necessary PVCs are created before the Pod

Beware that the webhook also gets called for pods which *don't* use TopoLVM. Enabling the webhook changes the behavior of the entire cluster for all pods. If the effect was limited to apps which explicitly want to use TopoLVM, then it would be perfectly fine to impose additional constraints like "PVC must be created first" - I'm less sure for other apps.

> We'd like to leave this as a limitation of TopoLVM for now.

That makes sense. I don't think there is a good solution anyway.

**Comment by ymmt2005** [comment]
@pohly 
Thank you for comments.  The webhook only cares pods with TopoLVM PVCs.

**Comment by pohly** [comment]
> The webhook only cares pods with TopoLVM PVCs.

But to determine that, it needs the PVC. Suppose a pod gets created with a PVC reference where the PVC has not been created yet and the PVC will not use TopoLVM. Then https://github.com/cybozu-go/topolvm/blob/7b79ee30e997a165b220d4519c784e50eaec36c8/hook/mutate_pod.go#L129-L136 triggers and the pod gets rejected although it has nothing to do with TopoLVM.

**Comment by ymmt2005** [comment]
That's true!

**Comment by satoru-takeuchi** [comment]
@pohly @ymmt2005 I changed my mind with Patrick's recent comments. I'd like to modify the webhook not to return error on PVCs absence. In addition, I'll add a description like "TopoLVM doesn't work correctly when PVC backed-by TopoLVM doesn't exist on pod creation" in `limitations.md`.

**Comment by binoue** [comment]
@pohly 

Like @satoru-takeuchi replied above, we implemented your commented issue in #99 .
Thanks for your contribution to TopoLVM. We appreciate it!
